### ISSUE TITLE
Model intra-organizational API-calls

### ISSUE THREAD

**Issue by adgerrits** [VNG-Realisatie/archi-sandbox#1]
Explicit model the requirements when a clientapplication calls a NLX-published API within the own organization. F.i. it may not be necessary to apply the same certificate-requirements as when calling remote API's.

**Comment by ehotting** [comment]
For now there is no difference at all. Organisation might want to make sure the traffic never leaves local network by means of routing / DNS. Will take a while before this can be drawn, not there yet in sprints
